# -*- coding: utf-8 -*-
"""00_ghg_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiq1tywmvdfKAygRf-64Sw4mTCujdoGb

# GHG modelling (CH4 & N2O)
This notebook loads monitoring data for 2023–2025, cleans values, maps emission factors (EFs) by process type, computes per-sample CH4 and N2O emission intensities using Equations (5.25) and (5.28), and saves results to `outputs/metrics/00_ghg_emissions.csv`.
Assumptions: `BOD` is treated as `BOD5`, `TN` = `NH3N + NO3N` (estimated), recovery terms assumed zero, default integrated EFs used unless overridden.

### 1. Nitrous Oxide ($N_2O$) Emissions
According to Equation 5.28 (pg. 52), the emission intensity for $N_2O$ is calculated as follows:

$$CES_{N_2O-ww} = (TN_{in} \times EF_{N_2O-ww} \times \frac{44}{28} \times 10^{-3} - M_{N_2O-T}) \times 265$$

**Where:**
*   **$CES_{N_2O-ww}$**: Emission intensity of $N_2O$ in wastewater treatment plant, kg $CO_2$-eq/$m^3$
*   **$TN_{in}$**: Average influent Kjeldahl nitrogen concentration of wastewater treatment plants, mg N/L
*   **$EF_{N_2O-ww}$**: Emission factor, kg $N_2O$-N/kg N (See Table 5.8)
*   **$M_{N_2O-T}$**: Recovered or removed amount of $N_2O$, kg $N_2O/m^3$
*   **$44/28$**: The conversion of kg $N_2O$-N into kg $N_2O$
*   **$265$**: Global warming potential of $N_2O$, kg $CO_2$-eq/kg $N_2O$

#### Table 5.8: $N_2O$ Emission Factors by Treatment Process
| Treatment Process | $N_2O$ EFs (kg $N_2O$-N/kg N) |
| :--- | :--- |
| **Integrated Emission Factor** | |
| Centralized, aerobic treatment plant | 0.0093 (General) / 0.0106 (China specific) |
| Anaerobic reactor (e.g., UASB) | 0 |
| Anaerobic deep lagoon | 0 |
| Anaerobic shallow lagoon | 0 ~ 0.001 |
| Aerated aerobic pond | 0 ~ 0.001 |
| **Emission factors by different processes** | |
| AAO | 0.00466 (9) |
| AO | 0.00680 (27) |
| Oxidation ditch | 0.00641 (13) |
| SBR | 0.02020 (11) |
| Aeration tank | 0.00166 (10) |
| Short-cut nitrification-ANAMMOX | 0.02000 (1) |
| Aerobic Granular Sludge | 0.00330 (1) |

### 2. Methane ($CH_4$) Emissions
According to Equation 5.25 (pg. 52), the emission intensity for $CH_4$ is calculated as follows:

$$CES_{CH_4-ww} = (BOD_{5in} \times EF_{CH_4-ww} - M_{CH_4-T}) \times 28 \times 10^{-3}$$

**Where:**
*   **$CES_{CH_4-ww}$**: Emission intensity of $CH_4$ in wastewater treatment plant, kg $CO_2$-eq/$m^3$
*   **$BOD_{5in}$**: Average influent $BOD_5$ concentration of wastewater treatment plant, mg $BOD_5$/L
*   **$EF_{CH_4-ww}$**: Emission factor, kg $CH_4$/kg $BOD_5$ (See Table 5.6)
*   **$M_{CH_4-T}$**: Recovered or removed amount of $CH_4$, kg $CH_4/m^3$
*   **$28$**: Global warming potential of $CH_4$, 28 kg $CO_2$-eq/kg $CH_4$

#### Table 5.6: $CH_4$ Emission Factors by Treatment Process
| Treatment Process | $CH_4$ EFs (kg $CH_4$/kg $BOD_5$) |
| :--- | :--- |
| **Integrated Emission Factor** | |
| Centralized, aerobic treatment plant | 0.0121 (0.000336 ~ 0.048) (General) |
| | 0.0036 (0.000336 ~ 0.0177) (China specific) |
| Anaerobic reactor (e.g., UASB) | 0.48 |
| Anaerobic deep lagoon | 0.5 |
| Anaerobic shallow lagoon | 0.125 |
| Aerated aerobic pond | 0.018 |
| **Emission factors by different processes** | |
| AAO | 0.0142 (7) |
| AO | 0.0083 (7) |
| Oxidation ditch | 0.0096 (4) |
| SBR | 0.0100 (3) |
| Aerobic tank | 0.0152 (6) |
"""

import pandas as pd
from pathlib import Path
import re

ROOT_DIR = Path.cwd()
if ROOT_DIR.name == 'notebooks':
    ROOT_DIR = ROOT_DIR.parent

DATA_DIR = ROOT_DIR / 'data'
OUT_DIR = ROOT_DIR / 'outputs' / 'metrics'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Default integrated emission factors
EF_CH4_GENERAL = 0.0121  # kg CH4 / kg BOD5
EF_N2O_GENERAL = 0.0093  # kg N2O-N / kg N
EF_MAP = {
    'SBR': {'ef_ch4': 0.0100, 'ef_n2o': 0.02020},
    'AAO': {'ef_ch4': 0.0142, 'ef_n2o': 0.00466},
    'AO': {'ef_ch4': 0.0083, 'ef_n2o': 0.00680},
    'Oxidation ditch': {'ef_ch4': 0.0096, 'ef_n2o': 0.00641},
    'Aeration tank': {'ef_ch4': 0.0152, 'ef_n2o': 0.00166},
    'ANAMMOX': {'ef_ch4': 0.0200, 'ef_n2o': 0.02000},
    'AGS': {'ef_ch4': 0.0033, 'ef_n2o': 0.00330},
}

def clean_numeric(x):
    if pd.isna(x):
        return None
    if isinstance(x, (int, float)):
        return x
    s = str(x).strip()
    s = re.sub(r'[<>]', '', s)
    s = s.replace(',', '')
    try:
        return float(s)
    except Exception:
        return None

def ensure_columns(df, columns):
    df = df.copy()
    for col in columns:
        if col not in df.columns:
            df[col] = pd.NA
    return df

def map_efs(stp_type):
    if not isinstance(stp_type, str):
        return EF_CH4_GENERAL, EF_N2O_GENERAL
    key = stp_type.strip()
    if key in EF_MAP:
        m = EF_MAP[key]
        return m.get('ef_ch4', EF_CH4_GENERAL), m.get('ef_n2o', EF_N2O_GENERAL)
    ku = key.upper()
    for k in EF_MAP:
        if k.upper() == ku:
            m = EF_MAP[k]
            return m.get('ef_ch4', EF_CH4_GENERAL), m.get('ef_n2o', EF_N2O_GENERAL)
    return EF_CH4_GENERAL, EF_N2O_GENERAL

def compute_emissions(df):
    df = df.copy()
    for col in ['BOD', 'NH3N', 'NO3N']:
        if col in df.columns:
            df[col] = df[col].apply(clean_numeric)
    df['BOD5'] = df['BOD'] if 'BOD' in df.columns else None
    df['TN_est'] = df[['NH3N', 'NO3N']].sum(axis=1, min_count=1)
    ch4_values = []
    n2o_values = []
    for _, row in df.iterrows():
        ef_ch4, ef_n2o = map_efs(row.get('STP_Type'))
        bod5 = row.get('BOD5')
        tn = row.get('TN_est')
        ch4 = (bod5 * ef_ch4) * 28 * 1e-3 if bod5 is not None else None
        n2o = (tn * ef_n2o * (44 / 28) * 1e-3) * 265 if tn is not None else None
        ch4_values.append(ch4)
        n2o_values.append(n2o)
    df['CH4_kgCO2e_m3'] = ch4_values
    df['N2O_kgCO2e_m3'] = n2o_values
    return df

REQUIRED_COLUMNS = ['Code', 'STP', 'Date', 'STP_Type', 'BOD', 'NH3N', 'NO3N', 'year']

dfs = []
for year in [2023, 2024, 2025]:
    path = DATA_DIR / f'{year}.csv'
    if not path.exists():
        print(f'Warning: {path} not found')
        continue
    df_year = pd.read_csv(path)
    df_year['year'] = year
    dfs.append(df_year)
df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame(columns=REQUIRED_COLUMNS)
print('Loaded rows:', len(df))
available_columns = list(df.columns)
missing_columns = [col for col in REQUIRED_COLUMNS if col not in df.columns]
df = ensure_columns(df, REQUIRED_COLUMNS)
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df = compute_emissions(df)
out_path = OUT_DIR / '00_ghg_emissions.csv'
df.to_csv(out_path, index=False)
print('Saved per-sample emissions to', out_path)

if len(df) > 0:
    summary = df.groupby(['Code', 'STP', 'year'], dropna=False).agg(
        CH4_count=('CH4_kgCO2e_m3', 'count'),
        CH4_mean=('CH4_kgCO2e_m3', 'mean'),
        CH4_median=('CH4_kgCO2e_m3', 'median'),
        N2O_count=('N2O_kgCO2e_m3', 'count'),
        N2O_mean=('N2O_kgCO2e_m3', 'mean'),
        N2O_median=('N2O_kgCO2e_m3', 'median'),
    ).reset_index()
else:
    summary = pd.DataFrame(columns=['Code', 'STP', 'year', 'CH4_count', 'CH4_mean', 'CH4_median', 'N2O_count', 'N2O_mean', 'N2O_median'])
summary_out_path = OUT_DIR / '00_ghg_emissions_station_year.csv'
summary.to_csv(summary_out_path, index=False)
print('Saved station/year summary to', summary_out_path)

df[['Code', 'STP', 'Date', 'BOD5', 'TN_est', 'STP_Type', 'CH4_kgCO2e_m3', 'N2O_kgCO2e_m3']].head(10)

"""**Notes and data requirements:**
- Required columns: `Code`, `STP`, `Date`, `STP_Type`, `BOD`, `NH3N`, `NO3N` (plus `year` added during load).
- `BOD` is used as `BOD5` for Equation (5.25).
- `TN` is estimated as `NH3N + NO3N` for Equation (5.28).
- Recovery terms are assumed zero because no recovery columns are present.
- The default EFs are the integrated general factors; process-specific EFs are applied when `STP_Type` matches known entries.

**Equation mapping:**
- CH4 (Eq. 5.25): `BOD` -> `BOD5`, `EF_CH4` from `STP_Type`, recovery = 0, GWP=28.
- N2O (Eq. 5.28): `NH3N + NO3N` -> `TN_est`, `EF_N2O` from `STP_Type`, recovery = 0, conversion = 44/28, GWP=265.
"""

# Emission factor coverage
known = df['STP_Type'].dropna().astype(str).apply(lambda x: map_efs(x) != (EF_CH4_GENERAL, EF_N2O_GENERAL))
print('Process-specific EF matches:', known.sum())
print('Total rows with STP_Type:', df['STP_Type'].notna().sum())
unmapped_types = df.loc[df['STP_Type'].notna() & ~known, 'STP_Type'].astype(str).unique()
print('Unmapped process types (count):', len(unmapped_types))
print('Unmapped examples:')
print(unmapped_types[:20])

# Sample emission results
print(df[['Code', 'STP', 'Date', 'BOD5', 'TN_est', 'STP_Type', 'CH4_kgCO2e_m3', 'N2O_kgCO2e_m3']].head(10).to_string(index=False))

# Station/year summary preview
print(summary.head(10).to_string(index=False))

