project_id = "citizenflood"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
auto_expose_new_tables = false

[db]
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "10MiB"

[auth]
enabled = true
site_url = "au.edu.monash.citizenflood://login-callback"
additional_redirect_urls = ["au.edu.monash.citizenflood://login-callback"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = true
enable_manual_linking = false
minimum_password_length = 8
password_requirements = "letters_digits"
