import json
from pathlib import Path
base=Path('.impeccable/mocks/decision')
def card(id,label,kicker,thesis,palette,materials,viewport,risk):
 return dict(id=id,label=label,kicker=kicker,thesis=thesis,palette=palette,materials=materials,viewport=viewport,risk=risk,comp=str(base/(id+'.png')))
a=card('assigned','Public water atlas','THE ROLL','Community reporting, wastewater work and research share one clear geographic index.',['#f3f1e7','#123e43','#537872','#c45e3c'],['cartographic linework','archival paper','precise legends'],'A wide annotated watershed drawing anchors a geographic index with a prominent APK download action.','Illustrative geography must never be mistaken for live monitoring data.')
a['raised']=[{'from':'Dark developer console','raise':'Actions and evidence classes gain strict separation and visible focus.'},{'from':'Loteria tabla','raise':'Each audience gets an unmistakably named entry point.'},{'from':'Sleeping city fold','raise':'The geographic composition remains continuous across the opening.'},{'from':'Hand-processed film','raise':'Reading order becomes a deliberate sequence rather than a card collection.'},{'from':'Nixie laboratory counter','raise':'Version and release state are legible facts rather than decorative numbers.'},{'from':'CRT arcade','raise':'A limited palette assigns one consistent meaning to each accent.'}]
p=card('model-pick','Research journal','IMPECCABLE’S PICK','A carefully edited research portal introduces the tools through evidence and plain language.',['#f7f5ee','#232f32','#476b70','#9d492f'],['publication rules','editorial typography','wide margins'],'A strong masthead and asymmetric editorial contents place download and account actions beside a clear platform introduction.','Familiar academic editorial styling could make the mobile app feel secondary.')
canon=card('canon','Conventional platform portal','','A familiar product introduction leads directly to downloads, accounts and research.',['#ffffff','#142b35','#236878'],['clean grid','quiet panels'],'A straightforward introduction, visible primary download action and clear product navigation.','The composition deliberately resembles other software portals.')
worlds=[('digital-design-canon-dark-first-developer-console','Dark developer console',['#181b20','#a8bac9'],'panel seams','An isolated release action in a graphite panel index.','Dense tool grammar makes public onboarding harder.','Public citizens identify less with developer tooling; panel navigation obscures the platform introduction.','Strict action separation.'),('vernacular-ephemera-loteria-tabla-night','Loteria tabla',['#f2cd42','#d94769','#39a9a1'],'numbered icon cards','A numbered table of downloads, workspace and research.','Game associations can weaken scientific interpretation.','Citizen recognition and evidence clarity are weaker than the atlas.','Clearly named entry points.'),('dream-surreal-impossible-worlds-sleeping-city-fold','Sleeping city fold',['#142346','#e1be74'],'quilted geography','Folded districts lead to community reports and research.','Dream imagery can imply unsupported flood conditions.','Surreal geography weakens both regional recognition and factual clarity.','Continuous geographic composition.'),('cinema-cinematography-editing-hand-processed-film-bloom','Hand-processed film',['#252321','#b66b35'],'film strips','A sequence of reporting, analysis and publications.','Photographic effects can disguise evidence quality.','Film treatment is less identifiable and makes source status harder to scan.','Deliberate reading sequence.'),('signals-instruments-nixie-tube-laboratory-counter','Nixie laboratory counter',['#201a16','#ef8b35'],'glass counters','Release and account entry points occupy a laboratory counter index.','Glowing counters could resemble measured live values.','Instrument symbolism is less familiar to citizens and obscures action hierarchy.','Precise release-state labeling.'),('medium-native-crt-arcade-pixel-glow','CRT arcade',['#111120','#ffe576'],'pixel grid','A strict tile index organizes the three platform journeys.','Arcade grammar trivializes civic reporting.','Gaming identification and pixel text weaken audience fit and reading clarity.','Consistent limited-palette semantics.')]
opts=[a,p]
for id,label,pal,mat,view,risk,case,kept in worlds:
 opts.append(dict(id=id,label=label,thesis='Translate the source grammar into the three platform journeys.',palette=pal,materials=[mat],viewport=view,risk=risk,verdict='declined',case=case,kept=kept))
payload=dict(title='Public portal: choose a visual direction',question='Compare the public water atlas with the research-journal alternative. These are visual concepts, not released functionality.',options=opts,reroll={'registers':['safer','bolder']},buildPath={'value':'comp','toggle':True},canon=True,canonCard=canon,steer=True)
Path('.impeccable/direction-options.json').write_text(json.dumps(payload,indent=2))
Path('docs/product/landing-direction-exploration.md').write_text('''# Landing direction exploration\n\nMode: Persuade. Status: awaiting user choice; no visual direction approved.\n\nMechanism: connect citizen observations and wastewater operations through a shared API, while keeping evidence classes explicit. The public visitor needs to find an Android download, account entry or approved research without understanding the internal architecture.\n\nGrounded candidates, ordered by audience resonance:\n1. Research journal: evidence-led editorial hierarchy.\n2. Civic information bulletin: public instructions and accountable ownership.\n3. Public water atlas: geographic context and explicit evidence legends.\n4. University exhibition catalog: methods, tools and reviewed research artifacts.\n5. Environmental field guide: approachable reporting instructions and definitions.\n6. Engineering standards publication: disciplined versioning and technical navigation.\n7. Community wayfinding system: unmistakable routes into the three purposes.\n\nThe concept seed selected candidate 3. The conventional software hero and its predictable dark technical counterpart are excluded from the grounded candidates. Catalog challengers were evaluated for audience identification and product clarity; their verdicts and retained disciplines are recorded on the decision board.\n\nAll previewed release/account actions represent planned capabilities. No invented paper, live metric, publication claim or institutional endorsement is permitted. The atlas must label illustrative geography and distinguish community observations, laboratory measurements and illustrative model outputs.\n''')
