"""Generate and verify a complete, pinned source-disposition inventory."""

import argparse
import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs/migration/source-inventory.json"
COMMITS = {
    "citizenflood": "5a80700",
    "dashboard": "202b72e",
    "api": "d518a95",
}
DISPOSITIONS = {"imported", "superseded", "legacy_reference", "generated", "restricted", "omitted"}


def git_bytes(repo: Path, *args: str) -> bytes:
    return subprocess.check_output(["git", "-C", str(repo), *args])


def tracked_paths(repo: Path, commit: str) -> list[str]:
    data = git_bytes(repo, "ls-tree", "-r", "-z", "--name-only", commit)
    return [part.decode() for part in data.split(b"\0") if part]


def source_bytes(repo: Path, commit: str, path: str) -> bytes:
    return git_bytes(repo, "show", f"{commit}:{path}")


def classify(repo: str, path: str) -> tuple[str, str | None, str | None]:
    if repo == "citizenflood":
        if path == "Monash Flutter App Dev.xlsx":
            return "restricted", None, "Project spreadsheet requires data-rights and personal-data review."
        if path == ".metadata":
            return "generated", None, "Flutter tool metadata is regenerated by the pinned SDK."
        if path.startswith("supabase/"):
            return "legacy_reference", f"legacy/supabase/citizenflood/{path.removeprefix('supabase/')}", None
        if path.startswith("docs/"):
            return "legacy_reference", f"docs/legacy/citizenflood/{path.removeprefix('docs/')}", None
        return "imported", f"apps/citizenflood/{path}", None

    if repo == "dashboard":
        if path.startswith(("backend/", "simulation/")):
            return "superseded", None, "Replaced by the pinned shared API foundation; origin retained here."
        if path.startswith("frontend/"):
            return "imported", f"apps/dashboard/{path.removeprefix('frontend/')}", None
        if path.startswith("public-data/"):
            return "imported", f"data/public/{path.removeprefix('public-data/')}", None
        if path in ("data-to-upload/2023.csv", "data-to-upload/2024.csv", "data-to-upload/2025.csv"):
            return "restricted", None, "Raw source CSV is outside the explicit public-data license; retain in controlled legacy checkout pending rights review."
        if path == "data-to-upload/00_ghg_modelling.py":
            return "legacy_reference", "legacy/research/00_ghg_modelling.py", None
        if path.startswith("data-to-upload/"):
            return "imported", f"research/data-preparation/{path.removeprefix('data-to-upload/')}", None
        if path.startswith("notebooks/"):
            return "imported", f"research/notebooks/{path.removeprefix('notebooks/')}", None
        if path == "scripts/export_public_dataset.py":
            return "legacy_reference", "legacy/scripts/dashboard/export_public_dataset.py", None
        if path.startswith("scripts/"):
            return "legacy_reference", f"legacy/scripts/dashboard/{path.removeprefix('scripts/')}", None
        if path.startswith("supabase/"):
            return "legacy_reference", f"legacy/supabase/dashboard/{path.removeprefix('supabase/')}", None
        if path == "LICENSE-DATA":
            return "imported", "data/public/LICENSE-DATA", None
        if path == ".gitignore":
            return "superseded", None, "Successor repository has one root ignore policy."
        if path.startswith("docs/"):
            return "legacy_reference", f"docs/legacy/dashboard/{path.removeprefix('docs/')}", None
        return "legacy_reference", f"docs/legacy/dashboard/{path}", None

    if repo == "api":
        if path.startswith("backend/"):
            return "imported", f"services/api/{path.removeprefix('backend/')}", None
        if path.startswith("simulation/"):
            return "imported", f"packages/simulation/{path.removeprefix('simulation/')}", None
        if path == "compose.test.yaml":
            return "imported", "infra/local/compose.test.yaml", None
        if path in ("pyproject.toml", "uv.lock"):
            return "imported", path, None
        if path == "scripts/export_openapi.py":
            return "imported", path, None
        if path == ".gitignore":
            return "superseded", None, "Successor repository has one root ignore policy."
        if path.startswith(".github/"):
            return "superseded", None, "Successor repository defines product-specific workflows."
        return "legacy_reference", f"docs/legacy/api/{path}", None

    raise ValueError(f"Unknown source: {repo}")


def build_manifest(sources: dict[str, Path]) -> dict:
    files = []
    for name, commit in COMMITS.items():
        repo = sources[name]
        for path in tracked_paths(repo, commit):
            disposition, target, reason = classify(name, path)
            entry = {
                "source_repo": name,
                "source_commit": commit,
                "source_path": path,
                "source_sha256": hashlib.sha256(source_bytes(repo, commit, path)).hexdigest(),
                "disposition": disposition,
            }
            if target:
                entry["target_path"] = target
            if reason:
                entry["reason"] = reason
            files.append(entry)
    return {"schema_version": 1, "source_commits": COMMITS, "files": files}


def validate(manifest: dict, sources: dict[str, Path], verify_targets: bool) -> None:
    assert manifest["source_commits"] == COMMITS
    rows = manifest["files"]
    assert len({(r["source_repo"], r["source_path"]) for r in rows}) == len(rows)
    targets = [r["target_path"] for r in rows if r.get("target_path")]
    assert len(targets) == len(set(targets)), "duplicate target paths"
    for row in rows:
        assert row["source_repo"] in COMMITS
        assert row["source_commit"] == COMMITS[row["source_repo"]]
        assert len(row["source_sha256"]) == 64 and all(c in "0123456789abcdef" for c in row["source_sha256"])
        disposition, target, reason = classify(row["source_repo"], row["source_path"])
        assert (row["disposition"], row.get("target_path"), row.get("reason")) == (disposition, target, reason), f"unclassified or stale disposition: {row['source_path']}"
        if target:
            assert not Path(target).is_absolute() and ".." not in Path(target).parts
            if verify_targets:
                assert (ROOT / target).is_file(), f"missing import: {target}"
    if not sources:
        return
    for name, commit in COMMITS.items():
        repo = sources[name]
        expected = set(tracked_paths(repo, commit))
        actual = {r["source_path"] for r in rows if r["source_repo"] == name}
        assert actual == expected, f"{name}: missing={expected-actual}, extra={actual-expected}"
        for row in (r for r in rows if r["source_repo"] == name):
            assert row["source_commit"] == commit
            assert row["disposition"] in DISPOSITIONS
            assert row["source_sha256"] == hashlib.sha256(
                source_bytes(repo, commit, row["source_path"])
            ).hexdigest(), f"source hash mismatch: {name}/{row['source_path']}"
            assert row.get("target_path") or row.get("reason")
            if verify_targets and row.get("target_path"):
                target = ROOT / row["target_path"]
                assert target.is_file(), f"missing import: {target}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", action="append", default=[], metavar="NAME=PATH")
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--verify-targets", action="store_true")
    args = parser.parse_args()
    sources = {name: Path(path) for name, path in (item.split("=", 1) for item in args.source)}
    assert not sources or set(sources) == set(COMMITS), f"required sources: {set(COMMITS)}"
    if args.generate:
        assert sources, "generation requires all pinned source checkouts"
        MANIFEST.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST.write_text(json.dumps(build_manifest(sources), indent=2, sort_keys=True) + "\n")
    validate(json.loads(MANIFEST.read_text()), sources, args.verify_targets)
    print(f"verified {len(json.loads(MANIFEST.read_text())['files'])} pinned source files")


if __name__ == "__main__":
    main()
