"""immutable simulation inputs and archive scenarios

Revision ID: 7f90bc451f01
Revises: f0f1cdd38975
Create Date: 2026-10-03 01:47:24.996054
"""

from alembic import op
import sqlalchemy as sa


revision = '7f90bc451f01'
down_revision = 'f0f1cdd38975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('simulation_runs', sa.Column('input_snapshot', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('simulation_runs', sa.Column('plant_snapshot', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('simulation_runs', sa.Column('scenario_snapshot', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('simulation_runs', sa.Column('artifact_digest', sa.String(), nullable=False, server_default='historical_unknown'))
    op.add_column('simulation_runs', sa.Column('validation_status', sa.String(), nullable=False, server_default='illustrative_unvalidated'))
    op.add_column('simulation_runs', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('simulation_runs', sa.Column('parent_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_run_parent', 'simulation_runs', 'simulation_runs', ['parent_run_id'], ['id'])
    for table, names in [('scenarios',['archived']),('simulation_runs',['input_snapshot','plant_snapshot','scenario_snapshot','artifact_digest','validation_status'])]:
        for name in names:op.alter_column(table,name,server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_run_parent', 'simulation_runs', type_='foreignkey')
    op.drop_column('simulation_runs', 'parent_run_id')
    op.drop_column('simulation_runs', 'error_code')
    op.drop_column('simulation_runs', 'validation_status')
    op.drop_column('simulation_runs', 'artifact_digest')
    op.drop_column('simulation_runs', 'scenario_snapshot')
    op.drop_column('simulation_runs', 'plant_snapshot')
    op.drop_column('simulation_runs', 'input_snapshot')
    op.drop_column('scenarios', 'archived')
    # ### end Alembic commands ###
