"""session MFA and operator login proof

Revision ID: c04995eb0733
Revises: 7f90bc451f01
Create Date: 2026-10-03 01:58:55.198064
"""

from alembic import op
import sqlalchemy as sa


revision = 'c04995eb0733'
down_revision = '7f90bc451f01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('browser_sessions', sa.Column('mfa_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('login_attempts', sa.Column('operator_login', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('browser_sessions','mfa_verified',server_default=None)
    op.alter_column('login_attempts','operator_login',server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_attempts', 'operator_login')
    op.drop_column('browser_sessions', 'mfa_verified')
    # ### end Alembic commands ###
